t = 0:0.001:1;
Am = 5;
Ac = 5;
fm = 10;
fc = 100;
k = 4;
m = Am*sin(2*pi*fm*t);
subplot(3,1,1);
plot(t,m);
title('Le signal modulant m(t)');
p = Ac*sin(2*pi*fc*t);
subplot(3,1,2);
plot(t,p);
title('Le signal porteur p(t)');
s = Ac*sin(2*pi*fc*t+k.*sin(2*pi*fm*t));
subplot(3,1,3);
plot(t,s);
title('Signal module s(t)');
print('pm', '-dpng', '-r300');
